language: perl

os:
  - linux
  # - osx

perl:
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

# This can be removed once CGI::Lingua 0.54 has been published
before_install:
  # Needed for Locale::Object
  - cpanm --installdeps --quiet --notest DBD::SQLite
  - cpanm --notest --quiet DBD::SQLite Locale::Object::Country
  - sudo apt-get update -q
  - sudo apt-get install -y libdb-dev

install:
  - cpanm --skip-satisfied --notest --quiet CGI::Carp CGI::Lingua File::Basename FCGI FCGI::Buffer File::HomeDir CGI::Buffer CHI::Driver::Null Cache::Memcached Log::Log4perl Config::Auto Template B::Lint Error::Simple warnings::unused HTML::SocialMedia Template::Plugin::EnvHash CGI::ACL Log::WarnDie Log::Dispatch::File XML::Simple DBD::CSV IPC::System::Simple autodie File::pfopen YAML:XS

script:
  - perl cgi-bin/index.fcgi ''
  - perl cgi-bin/index.pl ''
  - perl -MO=Lint cgi-bin/index.pl
  - perl -MO=Lint cgi-bin/index.fcgi
  - perl -c -Mwarnings::unused cgi-bin/index.pl
  - perl -c -Mwarnings::unused cgi-bin/index.fcgi
  - perl cgi-bin/index.fcgi person=nigel+horne
