os:
  - linux
  - osx
language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
# This can be removed once CGI::Lingua 0.54 has been published
before_install:
  # Needed for Locale::Object
  - cpanm --installdeps --no-interactive --verbose --notest DBD::SQLite
  - cpanm --notest --no-interactive --verbose DBD::SQLite Locale::Object::Country
install:
  - cpanm --installdeps --notest --no-interactive --verbose Log::Log4perl CGI::Carp CHI CGI::Lingua File::Basename FCGI FCGI::Buffer File::HomeDir
  - cpanm --notest --no-interactive --verbose Log::Log4perl CGI::Carp CHI CGI::Lingua File::Basename FCGI FCGI::Buffer File::HomeDir
script:
  - perl cgi-bin/index.fcgi
  - perl cgi-bin/index.pl
