os:
  - linux
  - osx
language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
# This can be removed once CGI::Lingua 0.54 has been published
before_install:
  # Needed for Locale::Object
  - cpanm --installdeps --quiet --notest DBD::SQLite
  - cpanm --notest --quiet DBD::SQLite Locale::Object::Country
install:
  - cpanm --installdeps --notest --no-interactive --verbose CGI::Carp CGI::Lingua File::Basename FCGI FCGI::Buffer File::HomeDir CGI::Buffer CHI::Driver::Memcached Cache::Memcached Log::Log4perl
  - cpanm --notest --no-interactive --verbose CGI::Carp CGI::Lingua File::Basename FCGI FCGI::Buffer File::HomeDir CGI::Buffer CHI::Driver::Memcached Cache::Memcached Log::Log4perl
script:
  - perl cgi-bin/index.fcgi ''
  - perl cgi-bin/index.pl ''
